// Code generated by entc, DO NOT EDIT.

package report

const (
	// Label holds the string label denoting the report type in the database.
	Label = "report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServerName holds the string denoting the server_name field in the database.
	FieldServerName = "server_name"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldDurationInSeconds holds the string denoting the duration_in_seconds field in the database.
	FieldDurationInSeconds = "duration_in_seconds"
	// Table holds the table name of the report in the database.
	Table = "reports"
)

// Columns holds all SQL columns for report fields.
var Columns = []string{
	FieldID,
	FieldServerName,
	FieldStartTime,
	FieldEndTime,
	FieldDurationInSeconds,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
